# Generated by Django 4.1 on 2022-10-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_alter_item_engraved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=260)),
                ('mobile_number', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=45)),
                ('zip_code', models.CharField(max_length=25, null=True)),
                ('city', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('delivery_payment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ordering_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sum_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('lineitem_sum', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('ordering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.ordering')),
            ],
        ),
    ]
