# Generated by Django 4.1 on 2022-10-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinglineitem',
            name='name_engraved',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
