# Generated by Django 4.1 on 2022-10-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
        ('checkout', '0003_ordering_original_bag_ordering_stripe_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='customer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='userprofiles.customerprofile'),
        ),
    ]
