# Generated by Django 4.1 on 2022-08-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='engraved',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
