# Generated by Django 4.1 on 2022-08-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_engraved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='engraved',
            field=models.CharField(blank=True, default=None, max_length=35, null=True),
        ),
    ]
