# Generated by Django 4.1 on 2022-10-09 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_mobile_number', models.CharField(blank=True, max_length=25, null=True)),
                ('default_country', models.CharField(blank=True, max_length=45, null=True)),
                ('default_zip_code', models.CharField(blank=True, max_length=25, null=True)),
                ('default_city', models.CharField(blank=True, max_length=50, null=True)),
                ('default_street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('web_site', models.CharField(blank=True, max_length=260, null=True)),
                ('want_wishes', models.TextField(blank=True, max_length=260, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
